# Generated by Django 5.1.2 on 2024-10-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCat', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductQuantity', models.IntegerField(blank=True, null=True)),
                ('ProductPrice', models.IntegerField(blank=True, null=True)),
                ('ProductDesc', models.TextField(blank=True, max_length=600, null=True)),
                ('ProductOrigin', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductMnfct', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductImage1', models.ImageField(blank=True, null=True, upload_to='Products')),
                ('ProductImage2', models.ImageField(blank=True, null=True, upload_to='Products')),
                ('ProductImage3', models.ImageField(blank=True, null=True, upload_to='Products')),
            ],
        ),
    ]
