# Generated by Django 5.1.2 on 2024-10-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ProductMnfct',
            new_name='ProductManu',
        ),
    ]
