# Generated by Django 5.1.2 on 2024-10-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UName', models.CharField(blank=True, max_length=100, null=True)),
                ('UContact', models.IntegerField(blank=True, null=True)),
                ('UEmail', models.EmailField(blank=True, max_length=100, null=True)),
                ('UPass', models.CharField(blank=True, max_length=100, null=True)),
                ('URPass', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
