# Generated by Django 5.1.2 on 2024-11-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='cartProduct/'),
        ),
    ]
